language: minimal
sudo: required
services: 
  - docker

before_install:
  - docker build -t logeshkumar/docker-react -f Dockerfile.dev .

script:
  - docker run logeshkumar/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "ap-south-1"  
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-175407317212"
  bucket_path: "docker-react"
  on:
    branch: master
