language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t logeshkumar/docker-react -f Dockerfile.dev .

scripts:
  - docker run logeshkumar/docker-react npm run test -- --coverage
