language: minimal
sudo: required
services: 
  - docker

before_install:
  - docker build -t logeshkumar/docker-react -f Dockerfile.dev .

script:
  - docker run logeshkumar/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstack
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-175407317212/?region=ap-south-1"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secret: "$AWS_SECRET_KEY"
